### ISSUE TITLE
should i set PYSDL2_DLL_PATH ?

### ISSUE THREAD

**Issue by f4h4m** [geohot/twitchslam#1]
Traceback (most recent call last):
  File "slam.py", line 9, in <module>
    from display import Display
  File "/home/gh0st/Desktop/twitchslam/display.py", line 1, in <module>
    import sdl2
  File "/usr/local/lib/python2.7/dist-packages/sdl2/__init__.py", line 2, in <module>
    from .dll import get_dll_file, _bind
  File "/usr/local/lib/python2.7/dist-packages/sdl2/dll.py", line 115, in <module>
    raise ImportError(exc)
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

**Comment by meh369** [comment]
Any clues how to fix this????
