### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Yeniceugur** [geohot/twitchslam#12]
gur@ugur-Mac ugur@ugur-Mac twitchslam-master % F=525 python3 slam.py videos/test_drone.mp4
pygame 2.0.1 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
using camera 1024x576 with F 140.000000
pygame 2.0.1 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html

*** frame 0/628 ***
Traceback (most recent call last):
  File "/Users/ugur/Public/twitchslam-master/slam.py", line 218, in <module>
    slam.process_frame(frame, None if gt_pose is None else np.linalg.inv(gt_pose[i]))
  File "/Users/ugur/Public/twitchslam-master/slam.py", line 31, in process_frame
    frame = Frame(self.mapp, img, self.K, verts=verts)
  File "/Users/ugur/Public/twitchslam-master/frame.py", line 84, in __init__
    self.id = tid if tid is not None else mapp.add_frame(self)
AttributeError: 'Map' object has no attribute 'add_frame'

PLEASE, HELP ME % F=525 python3 slam.py videos/test_drone.mp4
pygame 2.0.1 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
using camera 1024x576 

- 

> with F 140.000000

pygame 2.0.1 (SDL 2.0.14, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html

*** frame 0/628 ***
Traceback (most recent call last):
  File "/Users/ugur/Public/twitchslam-master/slam.py", line 218, in <module>
    slam.process_frame(frame, None if gt_pose is None else np.linalg.inv(gt_pose[i]))
  File "/Users/ugur/Public/twitchslam-master/slam.py", line 31, in process_frame
    frame = Frame(self.mapp, img, self.K, verts=verts)
  File "/Users/ugur/Public/twitchslam-master/frame.py", line 84, in __init__
    self.id = tid if tid is not None else mapp.add_frame(self)
AttributeError: 'Map' object has no attribute 'add_frame'

**Comment by Yeniceugur** [comment]
HELP ME , PLEASE

**Comment by chbGSmCm** [comment]
Please see https://github.com/geohot/twitchslam/issues/11 for a fix. You have installed the wrong pangolin.
